version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/collabsphere/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/collabsphere/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
